variable "aws_region" { }
variable "aws_profile" { }
variable "environment" { }
variable "app_name" { }
variable "bucket_name" { }
variable "working_dir" { }
variable "image_tag" { }
variable "ssm_parameter_token_name" { }
variable "ssm_parameter_key_name" { }